/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2016-07-13 03:06:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("\r\n");
      out.write("<!--use Enumeration, import package -->\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>TEST_headers</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

    Enumeration enu=request.getHeaderNames();//取得全部的头信息
    while(enu.hasMoreElements()){    //依次取出头信息
        String headerName=(String)enu.nextElement();
        String headerValue=request.getHeader(headerName);//取出头信息内容

      out.write("\r\n");
      out.write("    <h5>");
      out.print(headerName);
      out.write(" -- ");
      out.print(headerValue);
      out.write("</h5>\r\n");

    }

      out.write("\r\n");
      out.write("<h5>----RESPONSE----</h5>\r\n");
      out.write("<p></p>\r\n");
      out.write("<p></p>\r\n");

 String ct = response.getHeader("CLOUDWISE_TRACE");

      out.write("\r\n");
      out.write("<h5>CLOUDWISE_REQUEST_ID -- ");
      out.print(response.getHeader("CLOUDWISE_REQUEST_ID"));
      out.write("</h5>\r\n");
      out.write("<h5>CLOUDWISEREQUESTID -- ");
      out.print(response.getHeader("CLOUDWISEREQUESTID"));
      out.write("</h5>\r\n");
      out.write("<p></p>\r\n");
      out.write("<p></p>\r\n");
      out.write("<h5>CLOUDWISE_TRACE -- ");
      out.print(ct);
      out.write("</h5>\r\n");
      out.write("<h5>CLOUDWISETRACE -- ");
      out.print(response.getHeader("CLOUDWISETRACE"));
      out.write("</h5>\r\n");
      out.write("<h5>HeaderNames -- ");
      out.print(response.getHeaderNames());
      out.write("</h5>\r\n");
      out.write("<h5>Headers -- ");
      out.print(response.getHeaders("CLOUDWISE_TRACE"));
      out.write(' ');
      out.write('\r');
      out.write('\n');
      out.print(response.getHeaders("CLOUDWISETRACE"));
      out.write("</h5>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
