/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2017-08-08 02:06:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/resource/js/jquery-1.11.3.js\"></script>\r\n");
      out.write("    <title>MyBatis3.11 + Spring3.1.2 + Struts2</title>\r\n");
      out.write("<!--   <script>\r\n");
      out.write("    var CWRUMLICENCE = 'J45Engw88NchTUhqO1yVcnYn5/nOhfqv';\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"http://portal-qa.toushibao.com/rum/EndUserAgentPreload.js\"></script>\r\n");
      out.write("-->\r\n");
      out.write("<script> \r\n");
      out.write("\r\n");
      out.write("    window['adrum-start-time']= new Date().getTime();  \r\n");
      out.write("\r\n");
      out.write("    //'<app-key-for-this-app>'; \r\n");
      out.write("//       window['adrum-app-key'] = 'MyApp';\r\n");
      out.write("\r\n");
      out.write("</script> \r\n");
      out.write("\r\n");
      out.write(" <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resource/js/adrum.js\"></script>  \r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("jQuery(\"document\").ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tjQuery(\"#procedure\").click(function(){\r\n");
      out.write("\t\t//alert(\"123\");\r\n");
      out.write("\t\tjQuery(\"#student\").attr(\"action\",\"");
      out.print(request.getContextPath() );
      out.write("/student/updateAndSelect.action\");\r\n");
      out.write("\t\tjQuery(\"#student\").submit();\r\n");
      out.write("\t});\r\n");
      out.write("\tjQuery(\"#add\").click(function(){\r\n");
      out.write("\t\t//alert(\"123\");\r\n");
      out.write("\t\tjQuery(\"#student\").attr(\"action\",\"");
      out.print(request.getContextPath() );
      out.write("/student/addStudent.action\");\r\n");
      out.write("\t\tjQuery(\"#student\").submit();\r\n");
      out.write("\t});\r\n");
      out.write("\tjQuery(\"#sid\").change(function(){\r\n");
      out.write("\t\tvar sid = jQuery(this).val();\r\n");
      out.write("\t\tjQuery(\"#sname\").val(\"stu\"+sid);\r\n");
      out.write("\t\tjQuery(\"#major\").val(\"cc\");\r\n");
      out.write("\t\tjQuery(\"#score\").val(\"99.9\");\r\n");
      out.write("\t\tjQuery(\"#cid\").val(\"1\");\r\n");
      out.write("\t});\r\n");
      out.write("\tjQuery(\"#redisTest\").click(function(){\r\n");
      out.write("\t\t//alert(\"123\");\r\n");
      out.write("\t\tjQuery(\"#student\").attr(\"action\",\"");
      out.print(request.getContextPath() );
      out.write("/emp/redis.action\");\r\n");
      out.write("\t\tjQuery(\"#student\").submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tjQuery(\"#resturl\").click(function(){\r\n");
      out.write("\t\t//alert(\"123\");\r\n");
      out.write("\t\tjQuery(\"#student\").attr(\"action\",\"");
      out.print(request.getContextPath() );
      out.write("/student/resturl.action\");\r\n");
      out.write("\t\tjQuery(\"#student\").submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("function delstu(sid){\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({  \r\n");
      out.write("\t    url: \"");
      out.print(request.getContextPath() );
      out.write("/student/delStudentById.action?\", //调用的action  student.sid=\"+sid\r\n");
      out.write("\t    data: { 'student.sid':sid }, //请求的参数  \r\n");
      out.write("\t    type:'post',\r\n");
      out.write("\t    datatype:'json',\r\n");
      out.write("\t    success:function(data){  \r\n");
      out.write("\t    \t//alert(\"msg\"+data);\r\n");
      out.write("\t    \t$(\"#\"+sid).remove();\r\n");
      out.write("\t        $(\"#dbxl\").html(data);\r\n");
      out.write("\t    }  \r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  \t <form id=\"student\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/student/allStudent.action\" method=\"post\" >\r\n");
      out.write("     \t<table cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#F4F4F4\">\r\n");
      out.write("     \t\t<tr>\r\n");
      out.write("     \t\t\t<td>学生id</td>\r\n");
      out.write("     \t\t\t<td><input type=\"text\" id=\"sid\" name=\"student.sid\"/></td>\r\n");
      out.write("     \t\t\t<td>学生姓名</td>\r\n");
      out.write("     \t\t\t<td><input type=\"text\" id=\"sname\" name=\"student.sname\"/></td>\r\n");
      out.write("     \t\t</tr>\r\n");
      out.write("     \t\t<tr>\r\n");
      out.write("     \t\t\t<td>专业</td>\r\n");
      out.write("     \t\t\t<td><input type=\"text\" id=\"major\" name=\"student.major\"/></td>\r\n");
      out.write("     \t\t\t<td>得分</td>\r\n");
      out.write("     \t\t\t<td><input type=\"text\" id=\"score\" name=\"student.score\"/></td>\r\n");
      out.write("     \t\t</tr>\r\n");
      out.write("     \t\t<tr>\r\n");
      out.write("     \t\t\t<td>班级id</td>\r\n");
      out.write("     \t\t\t<td><input type=\"text\" id=\"cid\" name=\"student.cid\"/></td>\r\n");
      out.write("     \t\t\t<td>生日</td>\r\n");
      out.write("     \t\t\t<td><input type=\"date\" id=\"birth\" name=\"student.birth\"/></td>\r\n");
      out.write("     \t\t</tr>\r\n");
      out.write("     \t</table>\r\n");
      out.write("     \t<input type=\"submit\" value=\"全部\"/>\r\n");
      out.write("     \t<!-- <input type=\"button\" id=\"procedure\" value=\"修改姓名后测试oracle_procedure\"/> -->\r\n");
      out.write("     \t<input type=\"button\" id=\"redisTest\" value=\"跳转\" />\r\n");
      out.write("     \t<input type=\"button\" id=\"resturl\" value=\"RestURL\" />\r\n");
      out.write("     \t<input type=\"button\" id=\"add\" value=\"新增\"/>\r\n");
      out.write("     \t<span id=\"dbxl\" ></span>\r\n");
      out.write("     </form>\r\n");
      out.write("     <input type=\"button\" onclick=\"window.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/student/allStudent.action'\" value=\"获取所有学生\"/><br/>\r\n");
      out.write("     ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("     ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /index.jsp(119,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(stuList) > 0}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("     <table style=\"border: 1px solid blue;\" border=\"1px\" cellspacing=\"0\" bgcolor=\"#F4F4F4\">\r\n");
        out.write("     \t<tr align=\"center\">\r\n");
        out.write("     \t\t<td width=\"100px\">sid</td>\r\n");
        out.write("     \t\t<td width=\"100px\">sname</td>\r\n");
        out.write("     \t\t<td width=\"100px\">major</td>\r\n");
        out.write("     \t\t<td width=\"150px\">birth</td>\r\n");
        out.write("     \t\t<td width=\"100px\">score</td>\r\n");
        out.write("     \t\t<td width=\"100px\">操作</td>\r\n");
        out.write("     \t</tr>\r\n");
        out.write("     \t");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("     </table>\r\n");
        out.write("     ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /index.jsp(129,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/index.jsp(129,6) '${stuList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${stuList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /index.jsp(129,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("student");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("     \t<tr id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.sid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">\r\n");
          out.write("     \t\t<td width=\"100px\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.sid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("     \t\t<td width=\"100px\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.sname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("     \t\t<td width=\"100px\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.major}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("     \t\t<td width=\"180px\">");
          if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("<br></td>\r\n");
          out.write("     \t\t<td width=\"100px\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.score}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("     \t\t<td><input type=\"button\" onclick=\"delstu('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.sid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("')\" value=\"删除\"/> </td>\r\n");
          out.write("     \t</tr>\r\n");
          out.write("     ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /index.jsp(134,25) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.birth}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /index.jsp(134,25) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd HH:mm:ss");
    int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
    return false;
  }
}
