/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2017-09-28 09:13:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class restclient31_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/resource/js/jquery-1.11.3.js\"></script>\r\n");
      out.write("    <title>HttpClient-3.1</title>\r\n");
      out.write("<script> \r\n");
      out.write("\r\n");
      out.write("    // window['adrum-start-time']= new Date().getTime();  */\r\n");
      out.write("\r\n");
      out.write("    //'<app-key-for-this-app>'; \r\n");
      out.write("    //    window['adrum-app-key'] = 'MyApp';\r\n");
      out.write("\r\n");
      out.write("</script> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("jQuery(\"document\").ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tjQuery(\"#procedure\").click(function(){\r\n");
      out.write("\t\t//alert(\"123\");\r\n");
      out.write("\t\tjQuery(\"#student\").attr(\"action\",\"");
      out.print(request.getContextPath() );
      out.write("/student/updateAndSelect.action\");\r\n");
      out.write("\t\tjQuery(\"#student\").submit();\r\n");
      out.write("\t});\r\n");
      out.write("\tjQuery(\"#add\").click(function(){\r\n");
      out.write("\t\t//alert(\"123\");\r\n");
      out.write("\t\tjQuery(\"#student\").attr(\"action\",\"");
      out.print(request.getContextPath() );
      out.write("/student/addStudent.action\");\r\n");
      out.write("\t\tjQuery(\"#student\").submit();\r\n");
      out.write("\t});\r\n");
      out.write("\tjQuery(\"#sid\").change(function(){\r\n");
      out.write("\t\tvar sid = jQuery(this).val();\r\n");
      out.write("\t\tjQuery(\"#sname\").val(\"stu\"+sid);\r\n");
      out.write("\t\tjQuery(\"#major\").val(\"cc\");\r\n");
      out.write("\t\tjQuery(\"#score\").val(\"99.9\");\r\n");
      out.write("\t\tjQuery(\"#cid\").val(\"1\");\r\n");
      out.write("\t});\r\n");
      out.write("\tjQuery(\"#redisTest\").click(function(){\r\n");
      out.write("\t\t//alert(\"123\");\r\n");
      out.write("\t\tjQuery(\"#student\").attr(\"action\",\"");
      out.print(request.getContextPath() );
      out.write("/emp/redis.action\");\r\n");
      out.write("\t\tjQuery(\"#student\").submit();\r\n");
      out.write("\t});\r\n");
      out.write("})\r\n");
      out.write("function delstu(sid){\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({  \r\n");
      out.write("\t    url: \"");
      out.print(request.getContextPath() );
      out.write("/student/delStudentById.action?student.sid=\"+sid, //调用的action  \r\n");
      out.write("\t    data: {  }, //请求的参数  \r\n");
      out.write("\t    type:'post',\r\n");
      out.write("\t    datatype:'json',\r\n");
      out.write("\t    success:function(data){  \r\n");
      out.write("\t    \t//alert(\"msg\"+data);\r\n");
      out.write("\t    \t$(\"#\"+sid).remove();\r\n");
      out.write("\t        $(\"#dbxl\").html(data);\r\n");
      out.write("\t    }  \r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("     <H1>HttpClient-3.1</H1>\r\n");
      out.write("  \t <form id=\"student\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/student/restclient31.action\" method=\"post\" >\r\n");
      out.write("     \t<table cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#F4F4F4\" >\r\n");
      out.write("     \t\t<tr>\r\n");
      out.write("     \t\t\t<td>restURL</td>\r\n");
      out.write("     \t\t\t<td ><input type=\"text\" id=\"sname\" name=\"student.sname\" style=\"width:420px\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.sname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/></td>\r\n");
      out.write("     \t\t</tr>\r\n");
      out.write("     \t\t<tr>\r\n");
      out.write("     \t\t\t<td>result</td>\r\n");
      out.write("     \t\t\t<td ><input type=\"text\" id=\"major\" name=\"student.major\" style=\"width:420px\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.major}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("     \t\t\t<!-- <input type=\"hidden\" id=\"score\" name=\"student.score\"/>\r\n");
      out.write("     \t\t\t<input type=\"hidden\" id=\"sid\" name=\"student.sid\"/>\r\n");
      out.write("     \t\t\t<input type=\"hidden\" id=\"cid\" name=\"student.cid\"/>\r\n");
      out.write("     \t\t\t<input type=\"hidden\" id=\"birth\" name=\"student.birth\" /> -->\r\n");
      out.write("     \t\t\t</td>\r\n");
      out.write("     \t\t</tr>\r\n");
      out.write("     \t</table>\r\n");
      out.write("     \t<input type=\"submit\" value=\"testHttpClient-3.1\"/>\r\n");
      out.write("     \t<span id=\"dbxl\" ></span>\r\n");
      out.write("     </form>\r\n");
      out.write("     ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
